// <auto-generated/>
using Chefs.Services.Clients.Api.Recipe.Review.Dislike;
using Chefs.Services.Clients.Api.Recipe.Review.Like;
using Chefs.Services.Clients.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Chefs.Services.Clients.Api.Recipe.Review
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Recipe\review
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class ReviewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dislike property</summary>
        public global::Chefs.Services.Clients.Api.Recipe.Review.Dislike.DislikeRequestBuilder Dislike
        {
            get => new global::Chefs.Services.Clients.Api.Recipe.Review.Dislike.DislikeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The like property</summary>
        public global::Chefs.Services.Clients.Api.Recipe.Review.Like.LikeRequestBuilder Like
        {
            get => new global::Chefs.Services.Clients.Api.Recipe.Review.Like.LikeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReviewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Recipe/review{?userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReviewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Recipe/review{?userId*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Chefs.Services.Clients.Models.ReviewData"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Chefs.Services.Clients.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Chefs.Services.Clients.Models.ReviewData?> PostAsync(global::Chefs.Services.Clients.Models.ReviewData body, Action<RequestConfiguration<global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder.ReviewRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Chefs.Services.Clients.Models.ReviewData> PostAsync(global::Chefs.Services.Clients.Models.ReviewData body, Action<RequestConfiguration<global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder.ReviewRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Chefs.Services.Clients.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Chefs.Services.Clients.Models.ReviewData>(requestInfo, global::Chefs.Services.Clients.Models.ReviewData.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Chefs.Services.Clients.Models.ReviewData body, Action<RequestConfiguration<global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder.ReviewRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Chefs.Services.Clients.Models.ReviewData body, Action<RequestConfiguration<global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder.ReviewRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        #pragma warning disable CS1591
        public partial class ReviewRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("userId")]
            public Guid? UserId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ReviewRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Chefs.Services.Clients.Api.Recipe.Review.ReviewRequestBuilder.ReviewRequestBuilderPostQueryParameters>
        {
        }
    }
}
