// <auto-generated/>
#pragma warning disable CS0618
using Chefs.Client.Api.Cookbook;
using Chefs.Client.Api.Notification;
using Chefs.Client.Api.Recipe;
using Chefs.Client.Api.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Chefs.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Cookbook property</summary>
        public global::Chefs.Client.Api.Cookbook.CookbookRequestBuilder Cookbook
        {
            get => new global::Chefs.Client.Api.Cookbook.CookbookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Notification property</summary>
        public global::Chefs.Client.Api.Notification.NotificationRequestBuilder Notification
        {
            get => new global::Chefs.Client.Api.Notification.NotificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Recipe property</summary>
        public global::Chefs.Client.Api.Recipe.RecipeRequestBuilder Recipe
        {
            get => new global::Chefs.Client.Api.Recipe.RecipeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The User property</summary>
        public global::Chefs.Client.Api.User.UserRequestBuilder User
        {
            get => new global::Chefs.Client.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Chefs.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Chefs.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
